CREATE TABLE public.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);


ALTER TABLE public.usuario 
    ADD CONSTRAINT uc_usuario_username UNIQUE (username);